postgres_url: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
postgres_user: bars_kinder
postgres_databases:
  - bars_kinder
  - bars_kinder_service
  
