---
- name: Get OS type
  debug:
    var: ansible_facts.distribution

- name: Get OS type
  debug:
    var: ansible_user


- name: Update repositories latest postgres
  yum:
    name: '{{ postgres_url}}'


- postgresql_user:
    db: acme
    name: '{{ postgresql_user }}'
    password: '{{ postgres_password}}'

- name: Dump an existing database to a file (with compression)
  postgresql_db:
    name: '{{item}}'
  with_items: '{{ postgresql_db}}'


- name: GRANT ALL PRIVILEGES ON SCHEMA public, math TO librarian
  postgresql_privs:
    db: '{{item}}'
    privs: ALL
  with_items: '{{ postgresql_db}}'
