---
- name: Get OS type
  debug:
    var: ansible_facts.distribution

- name: Get OS type
  debug:
    var: ansible_user
- name: Update repositories latest postgres
  yum:
    name: '{{ postgres_url}}'
    state: present
    
- name: Update repositories latest postgres
  yum:
    name:
      - python3-pip
      - python2-pip
      - postgresql
      - postgresql-server
      - postgresql-libs
      - postgresql-contrib
      - postgresql-server-devel
    state: present

- name: Upda
  become: postgres
  pip:
    name:   psycopg2-binary
    extra_args: -i http://pip.robointerativo.ru/simple --trusted-host pip.robointerativo.ru
    #-
    # virtualenv: /tmp/venv
    # virtualenv_python: python3

# - postgresql_user:
#     db: acme
#     name: '{{ postgres_user }}'
#     password: '{{ postgres_password}}'
# #
# - name: Dump an existing database to a file (with compression)
#   postgresql_db:
#     name: '{{item}}'
#   with_items: '{{ postgresql_db}}'
#
#
# - name: GRANT ALL PRIVILEGES ON SCHEMA public, math TO librarian
#   postgresql_privs:
#     db: '{{item}}'
#     privs: ALL
#   with_items: '{{ postgresql_db}}'
